apiVersion: agents.speedscale.io/v1alpha1
kind: AgentApp
metadata:
  name: microsvc-user-service
spec:
  repo:
    provider: github
    url: https://github.com/speedscale/microsvc
    defaultBranch: master
    workdir: backend/user-service
  issue:
    labels:
      include:
        - agent
        - bug
  build:
    install: make build
    test: make test
    start: make run
  validate:
    proxymock:
      dataset: microsvc-user-service-404
      mode: replay-with-mocks
      command: make proxymock-replay
  policy:
    autoBranch: true
    autoMr: false
    autoMerge: false
