apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-factory
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - intake-api-service.yaml
  - intake-api-deployment.yaml
  - worker-deployment.yaml
images:
  - name: ghcr.io/speedscale/agent-factory
    newTag: v0.1.0
