apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - redis-service.yaml
  - redis-statefulset.yaml
patches:
  - path: intake-api-env.patch.yaml
  - path: worker-env-and-scale.patch.yaml
