apiVersion: apps/v1
kind: Deployment
metadata:
  name: intake-api
spec:
  template:
    spec:
      containers:
        - name: intake-api
          env:
            - name: INTAKE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: intake-api-auth
                  key: INTAKE_API_TOKEN
