apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
secretGenerator:
  - name: intake-api-auth
    literals:
      - INTAKE_API_TOKEN=change-me
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: intake-api-auth-env.patch.yaml
